[package]
name = "blog-platform-service"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version="0.5.1",features=["json"]}
time = { version = "0.3", features = ["macros", "formatting"] }
